- hosts: all
  become: true

  tasks:
    - name: Update the system and install Python and dependencies
      apt:
        update_cache: yes
        name:
          - python3
          - python3-pip
          - python3-venv
          - mariadb-client
        state: present

    - name: Ensure venv module is installed
      apt:
        name: python3-venv
        state: present

    - name: Remove existing virtual environment if it exists
      file:
        path: "{{ working_dir }}venv"
        state: absent
        force: yes

    - name: Set up the Python virtual environment
      command: python3 -m venv {{ working_dir }}venv
      args:
        creates: "{{ working_dir }}venv/bin/activate"

    - name: Activate the virtual environment and install dependencies
      shell: |
        source {{ working_dir }}venv/bin/activate
        pip install -r {{ working_dir }}requirements.txt
        pip install -e {{ working_dir }}
      args:
        executable: /bin/bash
